enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@firebase/*@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@nestjs/common@*":
    dependencies:
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/core@*":
    dependencies:
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/testing@*":
    dependencies:
      "@nestjs/common": "*"
      "@nestjs/core": "*"
      "@nestjs/platform-express": "*"
  "@nestjs/websockets@*":
    dependencies:
      "@nestjs/common": "*"
      "@nestjs/core": "*"
  "@testing-library/react@*":
    dependencies:
      "@testing-library/dom": "*"
  "@types/react@*":
    dependencies:
      react: "*"
  "@typescript-eslint/eslint-plugin@*":
    dependencies:
      eslint: "*"
  "@typescript-eslint/parser@*":
    dependencies:
      eslint: "*"
  eslint-plugin-jest@*:
    dependencies:
      typescript: "*"
  react-dom@*:
    dependencies:
      react: "*"
  "@cerebras/cerebras_cloud_sdk@*":
    dependencies:
      reflect-metadata: "*"
      
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
