version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.modified
    volumes:
      - ./apps/frontend/src:/project/apps/frontend/src
      - ./apps/frontend/public:/project/apps/frontend/public
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: yarn dev --host 0.0.0.0
