# Information Architecture Monitoring Configuration

# Metrics Collection
metrics:
  # Document Structure Compliance
  structure:
    - name: schema_compliance
      type: percentage
      description: "Percentage of documents following master schema"
      threshold: 95
    - name: cross_reference_validity
      type: percentage
      description: "Percentage of valid cross-references"
      threshold: 98

  # Data Exchange Standards
  data_exchange:
    - name: mcp_protocol_compliance
      type: percentage
      description: "Compliance with MCP protocol standards"
      threshold: 100
    - name: message_format_validity
      type: percentage
      description: "Message format compliance rate"
      threshold: 99

  # Integration Standards
  integration:
    - name: api_compliance
      type: percentage
      description: "API compliance with master architecture"
      threshold: 98
    - name: integration_pattern_adherence
      type: percentage
      description: "Adherence to defined integration patterns"
      threshold: 95

# Alerts Configuration
alerts:
  critical:
    - metric: schema_compliance
      threshold: 90
      duration: 1h
      action: notify_architecture_team
    - metric: mcp_protocol_compliance
      threshold: 95
      duration: 5m
      action: notify_dev_team

  warning:
    - metric: cross_reference_validity
      threshold: 95
      duration: 6h
      action: notify_docs_team
    - metric: integration_pattern_adherence
      threshold: 90
      duration: 24h
      action: notify_integration_team