apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-new-fuse
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: the-new-fuse
  template:
    metadata:
      labels:
        app: the-new-fuse
    spec:
      containers:
      - name: api
        image: gcr.io/the-new-fuse-2025/api:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: monitoring
        image: gcr.io/the-new-fuse-2025/monitoring:latest
        ports:
        - containerPort: 9090
