apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fuse-frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - fuse.example.com
    secretName: fuse-tls
  rules:
  - host: fuse.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fuse-frontend
            port:
              number: 80