apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fuse-api-monitor
spec:
  selector:
    matchLabels:
      app: fuse-api
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fuse-api-alerts
spec:
  groups:
  - name: fuse-api
    rules:
    - alert: HighErrorRate
      expr: |
        sum(rate(http_requests_total{status=~"5.."}[5m])) 
        / 
        sum(rate(http_requests_total[5m])) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: Error rate is above 10% for 5 minutes

    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: 95th percentile latency is above 2 seconds

    - alert: HighMemoryUsage
      expr: |
        container_memory_usage_bytes{container="fuse-api"} 
        / 
        container_spec_memory_limit_bytes{container="fuse-api"} > 0.85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: Memory usage is above 85% for 10 minutes

    - alert: HighCPUUsage
      expr: |
        sum(rate(container_cpu_usage_seconds_total{container="fuse-api"}[5m])) 
        / 
        sum(container_spec_cpu_quota{container="fuse-api"}) > 0.85
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage detected
        description: CPU usage is above 85% for 10 minutes
