apiVersion: apps/v1
kind: Deployment
metadata:
  name: thefuse
  namespace: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: thefuse
  template:
    metadata:
      labels:
        app: thefuse
      annotations:
        checksum/config: ${CONFIG_CHECKSUM}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: thefuse
        image: thefuse:${VERSION_TAG}
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9090
          name: metrics
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
        startupProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: thefuse-secrets
              key: database-url
        - name: FEATURE_FLAGS
          value: "canary_features=false,beta_testing=false"
        - name: DEPLOYMENT_VALIDATION
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
      initContainers:
      - name: validation-check
        image: thefuse-validator:latest
        env:
        - name: VALIDATION_TYPE
          value: production
        - name: MIN_TEST_COVERAGE
          value: "90"
        - name: CHECK_SECURITY_ISSUES
          value: "true"
        - name: CHECK_PERFORMANCE_METRICS
          value: "true"
      - name: db-migrations
        image: thefuse:${VERSION_TAG}
        command: ['npm', 'run', 'migrate']
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: thefuse-secrets
              key: database-url
      imagePullSecrets:
      - name: registry-credentials