# Information Architecture Monitoring Configuration

# Metrics Collection
metrics:
  # Document Structure Compliance
  structure:
    - name: schema_compliance
      type: percentage
      description: "Percentage of documents following master schema"
      threshold: 95
    - name: cross_reference_validity
      type: percentage
      description: "Percentage of valid cross-references"
      threshold: 98

  # Data Exchange Standards
  data_exchange:
    - name: mcp_protocol_compliance
      type: percentage
      description: "Compliance with MCP protocol standards"
      threshold: 100
    - name: message_format_validity
      type: percentage
      description: "Message format compliance rate"
      threshold: 99

  # Integration Standards
  integration:
    - name: api_compliance
      type: percentage
      description: "API compliance with master architecture"
      threshold: 98
    - name: integration_pattern_adherence
      type: percentage
      description: "Adherence to defined integration patterns"
      threshold: 95

# Alerts
alerts:
  critical:
    - metric: schema_compliance
      threshold: 90
      duration: 1h
      action: notify_architecture_team
    - metric: mcp_protocol_compliance
      threshold: 95
      duration: 5m
      action: notify_dev_team

  warning:
    - metric: cross_reference_validity
      threshold: 95
      duration: 6h
      action: notify_docs_team
    - metric: integration_pattern_adherence
      threshold: 90
      duration: 24h
      action: notify_integration_team

# Health Checks
health_checks:
  # Document Validation
  document:
    - name: schema_validation
      interval: 1h
      timeout: 30s
    - name: cross_reference_check
      interval: 6h
      timeout: 2m

  # Integration Validation
  integration:
    - name: api_schema_validation
      interval: 15m
      timeout: 30s
    - name: message_format_validation
      interval: 5m
      timeout: 10s

# Dashboards
dashboards:
  - name: architecture_compliance
    refresh: 5m
    panels:
      - name: Schema Compliance Trends
        type: line_graph
        metrics:
          - schema_compliance
          - cross_reference_validity
      - name: Protocol Standards
        type: gauge
        metrics:
          - mcp_protocol_compliance
          - message_format_validity
      - name: Integration Health
        type: status_grid
        metrics:
          - api_compliance
          - integration_pattern_adherence

# Logging
logging:
  compliance_changes:
    level: info
    retention: 90d
  standard_violations:
    level: warn
    retention: 180d
  security_events:
    level: error
    retention: 365d

# Reporting
reports:
  daily:
    - name: compliance_summary
      metrics:
        - schema_compliance
        - mcp_protocol_compliance
        - api_compliance
      format: html
      recipients: architecture_team
  weekly:
    - name: detailed_compliance
      metrics: all
      format: pdf
      recipients: [architecture_team, dev_leads]
  monthly:
    - name: trend_analysis
      metrics: all
      format: pdf
      recipients: [architecture_team, dev_leads, management]

# Integration Points
integrations:
  - name: prometheus
    type: metrics
    endpoint: http://prometheus:9090
  - name: grafana
    type: visualization
    endpoint: http://grafana:3000
  - name: elasticsearch
    type: logging
    endpoint: http://elasticsearch:9200