name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Run SAST Scan
        uses: github/codeql-action/analyze@v2

  deploy-staging:
    needs: security-scan
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name fuse-staging
          helm upgrade --install fuse ./charts/fuse \
            --namespace staging \
            --set image.tag=${GITHUB_SHA} \
            --values ./charts/fuse/values-staging.yaml

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://api.fuse.production
    steps:
      - name: Deploy to Production
        run: |
          aws eks update-kubeconfig --name fuse-production
          helm upgrade --install fuse ./charts/fuse \
            --namespace production \
            --set image.tag=${GITHUB_SHA} \
            --values ./charts/fuse/values-production.yaml